language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

before_script:
  - cp .env.example .env
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/phpspec run --no-interaction
