language: php

services: mysql

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

before_script:
  - cp .env.travis .env
  - composer install
  - mysql -e 'CREATE DATABASE myapp_test;'
  - php artisan doctrine:schema:create
  - php artisan app:load:fixtures

script:
  - vendor/bin/phpunit
  - vendor/bin/phpspec run --no-interaction
